### ISSUE TITLE
ensure compatibility with linebreaker package

### ISSUE THREAD

**Issue by hpvd** [gucci-on-fleek/lua-widow-control#18]
Since lua widow control and [linebreaker package](https://github.com/michal-h21/linebreaker) (which seems to be release soon)
both work on optimizing typesetting results in fully automated fashion,
it would be great if one could take care to keep them compatible/playing well with each other.

**Comment by hpvd** [comment]
this is the corresponding issue at linebreaker package:
https://github.com/michal-h21/linebreaker/issues/3 

There was already a first comment on compatibility from @michal-h21
> I don't know much about this package, but from what I saw in the source code, one possible issue is that both of these packages sets the `hpack_quality` callback. Linebreaker uses it to record badness, but `lua-widow-control` adds empty callback, which removes the overfull box warning.
> 
> I've tried to use `\usepackage{lua-widow-control}` in the documentation both before, and after \usepackage{linebreaker}, and seems that it doesn't have a negative impact on Linebreaker. I don't know about the impact on the widow control, as I don't have an example for testing.

**Comment by gucci-on-fleek** [comment]
See my comment at [michal-h21/linebreaker#3](https://github.com/michal-h21/linebreaker/issues/3#issuecomment-1046190147).

**Comment by gucci-on-fleek** [comment]
- [ ] Add `\usepackage{linebreaker}` to `tests/latex-advanced.tex`
