### ISSUE TITLE
Lua-widow-control breaks section titles

### ISSUE THREAD

**Issue by lodumont** [gucci-on-fleek/lua-widow-control#30]
### Issue

I wanted to test the lua-widow-control package along with the memoir class to write my dissertation. I found out some section titles were broken into several lines. In the log file, this is always on the page a widow or orphan is detected. I was unable to reproduce this behaviour in a MWE...

<img width="410" alt="Capture d’écran 2022-03-16 à 12 27 38" src="https://user-images.githubusercontent.com/61599071/160448163-14ffeafd-32eb-484e-8742-ebe8eeb27fce.png">
<img width="556" alt="Capture d’écran 2022-03-28 à 18 45 36" src="https://user-images.githubusercontent.com/61599071/160448174-57900c6e-a819-4216-aaec-340fbb97b7b9.png">

### Expected Behavior

I expected that lua-widow-control wouldn't introduce linebreak in the section titles.

### Format

LaTeX

### Distribution

TeX Live

### Distribution Version

TeX Live 2021

### Lua-widow-control Version

v. 2.0.2

**Comment by gucci-on-fleek** [comment]
It's in the documentation, although it's pretty hidden.

[Bottom of page 10:](https://texdoc.org/serve/lua-widow-control/0#%2353)
> Sometimes, you may want to disable lua-widow-control for certain commands where stretching is undesirable. For example, you typically wouldn't want section headings to be stretched. […] Lua-widow-control does not patch the non-standard section commands provided by memoir, KOMA-script, titlesec, OpTeX, and others. You'll need to add these yourself.

---

Try replacing
```latex
\usepackage{lua-widow-control}
```
with
```latex
\makeatletter
\usepackage[disablecmds={\noexpand\M@sect, \noexpand\@mem@old@ssect}]{lua-widow-control}
\makeatother
```

That should _hopefully_ fix the problem. Let me know if that doesn't work.

Admittedly, this is a pretty user-hostile interface. I should probably be patching the memoir/koma/titlesec commands by default since they are so popular. I'll make this behavior automatic in a future update.

**Comment by gucci-on-fleek** [comment]
Fixed in a68ec0ca411022c8e5624b17c992a7bdb16c62d2

**Comment by gucci-on-fleek** [comment]
Alright, v2.0.3 should patch these commands automatically. I've uploaded it to CTAN, so future versions of lua-widow-control shouldn't need the cryptic commands from above.

However, TeX Live 2021 is frozen, and TeX Live 2022 won't be released until April 3rd, so it's going to be about a week until any lua-widow-control updates actually show up. In the meantime, the code from above should solve the issue. You can also manually install [the updated version](https://github.com/gucci-on-fleek/lua-widow-control/releases/tag/release-d6622dd9fd04a4bc7678ff18420c1b4bdf077844) if you prefer.

**Comment by lodumont** [comment]
Sorry, I missed that part in the documentation... Anyway thank you, that solved my problem.
