### ISSUE TITLE
Misplaced header with memoir class

### ISSUE THREAD

**Issue by lodumont** [gucci-on-fleek/lua-widow-control#31]
### Issue

I am using the memoir class to tyepset a document with header displaying chapter number and title on even pages and section number and title on odd ones. I am using the following commands:

```
\makeevenhead{fancy}{}{\leftmark}{}
\makeoddhead{fancy}{}{\rightmark}{}
```

Using lua-widow-control v. 2.0.3, I get the wrong header at random locations on the page, as showed on the examples below. These misplaces headers also replace some text that simply disappear. As this is taken from a very large document, I was unable to reproduce this behaviour with a MWE.

<img width="595" alt="Capture d’écran 2022-04-06 à 13 48 11" src="https://user-images.githubusercontent.com/61599071/161968586-d8b2b2fd-9fd2-4eb5-8e1e-8c0d918857ce.png">
<img width="595" alt="Capture d’écran 2022-04-06 à 13 49 45" src="https://user-images.githubusercontent.com/61599071/161968595-ca50b941-28be-43d8-aaaa-c2378494f412.png">
s

### Expected Behavior

I expect lua-widow-control to respect the header position using the memoir class

### Format

LaTeX

### Distribution

TeX Live

### Distribution Version

TeX Live 2022

### Lua-widow-control Version

2.0.3

**Comment by gucci-on-fleek** [comment]
Looks like memoir puts the headers/footers in a `\parbox`, meaning that a paragraph is being typeset _during_ the output routine, which is something that I wasn't expecting.

Try placing
```latex
\lwcsetup{disablecmds={M@sect, @mem@old@ssect, @oddhead, @oddfoot, @evenhead, @evenfoot}}
```
in your preamble after you load lua-widow-control. Let me know if that works or not.

**Comment by lodumont** [comment]
Thank you, that solved my issue! I was expected something like that but I couldn't determine the memoir's macros that were involved.

**Comment by gucci-on-fleek** [comment]
Good to hear. I'll get this in v2.0.4 and send it off to CTAN shortly. It should be in TeX Live in ~2 days, after which you won't need the workaround I posted.

And thanks for the report!
