### ISSUE TITLE
new option: only find don't fix

### ISSUE THREAD

**Issue by hpvd** [gucci-on-fleek/lua-widow-control#36]
Since with the latest updates of this great package, the number of warnings is normalized/cleaned up,
it would be great to understand/analyse the value of this package by having a new option: `only find dont fix`
(and warn).

With this, one could easily compare the impact of this package between two runs
1. first standard/default behaviour (find AND fix)
2. with the new option set (only find, don't fix)

When looking into logs one could then simply compare the number of warnings

With such an option one do not have to rely on other package which may use other standard for counting...

**Comment by hpvd** [comment]
this would also be a great help when trying the different package modes (default/strict/balanced) or figuring out the advanced settings with long realworld documents...

**Comment by gucci-on-fleek** [comment]
You can use the `disable` option (or `enable=false` or `\lwcdisable`).

This example:
```latex
\documentclass{article}

\usepackage[disable]{lua-widow-control}

\begin{document}

\vspace*{44\baselineskip}

This line has a widow \emph{and} an orphan. This line has a widow
\emph{and} an orphan. This line has a widow \emph{and} an orphan.

\end{document}
```
gives this ouput:
```log
Module lua-widow-control Warning: Widow/Orphan/broken hyphen NOT removed on page 1 on input line 12
```

This works well, but there is a caveat: by shifting the layout of earlier pages, lua-widow-control can inadvertently create new widows/orphans later on. This doesn't happen too often, but it does mean that just comparing warning counts may be misleading. Example:
```latex
\documentclass{article}

% Option A
\usepackage[disable]{lua-widow-control}

% Option B
% \usepackage[enable]{lua-widow-control}

\def\longexample{%
    One two three four five six seven eight nine ten. One two three
    four five six seven eight nine ten. One two three four five six
    seven eight nine ten. One two three four five six seven eight nine
    ten. One two three four five six seven eight nine ten. One two
    three four five six seven eight nine ten. One two three four five
    six seven eight nine ten. One two three four five six seven eight
    nine ten. One two three four five six seven eight nine ten. One
    two three four five six seven eight nine ten. One two three four
    five six seven eight nine ten. One two.\par%
}

\def\shortexample{%
    One two three four five six seven eight nine ten. One two three
    four five six seven eight nine ten. One two three four five six
    seven eight nine ten. One two three four five six seven eight nine
    ten. One two three four five six seven eight nine ten.\par%
}

\begin{document}
    \vspace*{28\baselineskip}

    \longexample
    \longexample
    \shortexample

    \vspace*{41\baselineskip}

    \shortexample
\end{document}
```
Output A:
```log
Module lua-widow-control Warning: Widow/Orphan/broken hyphen NOT removed on page 1 on input line 38
```
Output B:
```log
Module lua-widow-control Warning: Widow/Orphan/broken hyphen NOT removed on page 2 on input line 39
```

---

If your goal is just to see how many widows/orphans were removed, a better method would be to count the occurrences of 
```log
Module lua-widow-control Info: Widow/orphan/broken hyphen successfully removed
```
in the log file. This is how I produced [figure 5 in the TUGboat article](https://ctan.math.ca/tex-archive/macros/luatex/generic/lua-widow-control/tb133chernoff-widows.pdf#page=11).

**Comment by hpvd** [comment]
many thanks for giving all the details!

did some counting ;-)
Module lua-widow-control Info: Widow/orphan/broken hyphen successfully removed: 27

4 new warnings of type:
Module lua-widow-control Warning: Making a new widow/orphan/broken hyphen on page 46 on input line 2457

=> these warnings, are probably correct about the place of "Making" these new w/o/bh
when using the comfort of editors and click on the warning to jump to the place to check how worse it looks like,
first to the line in .tex than from there with an other click to the place in .pdf
one has to scroll around/search to find the place where it is.

e.g. widows are typical visible on the next side (what's somehow logical) so in example above you have to scroll to page 47
but sometimes it's not the logical at at all....

so the question: do you have full control about the lines and pages shown or is it tex internal?

**Comment by hpvd** [comment]
(since this is a new topic, should I move it to a new issue, so this one could be closed independently?)

**Comment by gucci-on-fleek** [comment]
> do you have full control about the lines and pages shown or is it tex internal?

The page number I am printing myself, but the line number is from LaTeX itself. 

https://github.com/gucci-on-fleek/lua-widow-control/blob/ef59691b69b1a248550fb94eb176a5dd3fc13a3f/source/lua-widow-control.lua#L605-L611

The "page" will always be the page where the issue _begins_. In the case of orphans/broken hyphens, this is the same page where the issue "appears". For widows, the issue "appears" on the following page, although I don't think that it's possible for lua-widow-control to make a new widow.

> would it be possible to hint to the place where the "problem" appears/becomes visible?

With the current warnings, I'm pretty sure that the location is always going to be the last line of the listed page. The only time (I think) when it would be visible at a different location is when lua-widow-control fails to remove a widow; then the issue is only visible on the first line of the following page. Even in this case, the message is still fairly helpful, since to remove the widow you would need to fix the listed page.

> since this is a new topic, should I move it to a new issue, so this one could be closed independently?

Doesn't really matter :)

**Comment by hpvd** [comment]
Ok, thanks again :-)

I’m just on the route to make quality of documents "bulletproof for people who do not have an eye for this"
what do you think about adding an option for visual debugging?

e.g.
- orange background for new introduced widows/orphans
- red for not removed widows/orphans

**Comment by gucci-on-fleek** [comment]
> What do you think about adding an option for visual debugging?

Seems like a good idea, so I've implemented it in the [newest beta](https://github.com/gucci-on-fleek/lua-widow-control/releases/tag/release-b0dcc3ed32642731fc4514af89760d639271c76b). Let me know if you have any feedback.

**Comment by hpvd** [comment]
yeah, that is very nice!

many thanks for your work on this :-)

just two comments:
- in twoside documents, using on each site the right margin to show the cost may lead to cut numbers, because on every second site the right margin is the inner margin which often is narrow...
- a possibility to set the colors for highlighting would be the ice on the cake to prevent interference with other coloring efforts in the document ( e.g. other visual debugging, color usage for collaboration etc.)

**Comment by gucci-on-fleek** [comment]
> in twoside documents, using on each site the right margin to show the cost, may lead to cut numbers, because on every second site the right margin is the inner margin which often is pretty narrow...

Your point is definitely correct, but it would be tricky to detect which "side" each page is on. Instead, I've just shrunk the font size for the cost numbers.

> a possibility to set the colors for highlighting would be the ice on the cake to prevent interference with other coloring efforts in the document ( e.g. other visual debugging, color usage for collaboration etc.)

Sure. It's not a very polished interface, but you can do something like
```tex
\directlua{lwc.colours.failure = {1, 0.5, 1}}
```
which would set the widow/orphan colour to pink. The values are RGB, so `{1, 0, 0}` is red, `{0, 1, 1}` is teal, `{0, 0, 0}` is black, etc.

This is all in the [newest beta](https://github.com/gucci-on-fleek/lua-widow-control/releases/tag/release-e9fbd215baa80ea596f4e17cd0eb0bf34d7eb630). And thanks for the feedback!

**Comment by gucci-on-fleek** [comment]
This is in [v2.2.0](https://github.com/gucci-on-fleek/lua-widow-control/releases/tag/release-9a5deba53545adc5ab25a5caa0b8ebf4104843f9), which has been sent of to CTAN.
