### ISSUE TITLE
How does this package compare to the `nowidow` package?

### ISSUE THREAD

**Issue by amarakon** [gucci-on-fleek/lua-widow-control#42]
I tested both the `nowidow` and `lua-widow-control` packages in a bilingual document with English and Arabic. Both of them did not result in all of the widows and orphans being eliminated, but they both reduced the amount of them. However, `nowidow` yielded in better results than `lua-widow-control`: fewer orphans and widows. 

1. Why is it that `lua-widow-control` cannot eliminate all the widows and orphans in the document?
2. What will happen if I load both of these packages in the same document? Will this result in the fewest widows and orphans possible?

**Comment by gucci-on-fleek** [comment]
`nowidow` is equivalent to “Stretch” in the image below (from [page 6 of the manual](https://texdoc.org/serve/lua-widow-control/0#page=6)) with document classes `book` and `report`, and “Shorten” with document class `article`. Lua-widow-control is unsurprisingly equivalent to “Lua-widow-control”.

![image](https://github.com/gucci-on-fleek/lua-widow-control/assets/49086429/ecf22a89-2e93-4c6c-a894-58716282d6c2)

> 1\. Why is it that lua-widow-control cannot eliminate all the widows and orphans in the document?

Lua-widow-control in its default settings usually removes >95% of (potential) widows and orphans. There are some graphs in [§15 of the _Zpravodaj_ article](https://texdoc.org/serve/lua-widow-control/3#page=23) and some further discussion in §16. 

Some relevant portions are quoted below:

> There are, however, some fundamental limitations due to how lua-widow-control operates:
> 
> - When a three-line paragraph is at the end of a page forming a widow, lua-widow-control will remove the widow; however, it will leave an orphan. This issue is inherent to any process that removes widows through paragraph expansion and is thus unavoidable. Orphans are considered to be better than widows (Bringhurst, 2004), so this is still an improvement.
> 
> - Sometimes a widow or orphan cannot be eliminated because no paragraph has enough stretch. Sometimes this can be remediated by increasing lua-widow-control’s `\emergencystretch`; however, some pages just don’t have any suitable paragraph. Long paragraphs with short words tend to be stretchier than short para- graphs with long words since these long paragraphs have more interword glue. Narrow columns also stretch more easily than wide columns since you need to expand a paragraph by less to make a new line.
> 
> - lua-widow-control only attempts to expand paragraphs on a page with a widow or orphan. A global system like in “A general framework for globally optimized pagination” (Mittelbach, 2018a) would solve this; however, this is both NP-complete (Plass, 1981) and impossible to solve in a single pass. Very rarely would such a system remove widows or orphans that lua-widow-control cannot.

If you want lua-widow-control to try _really_ hard, you can try something like

```tex
\lwcsetup{emergencystretch = \maxdimen}
```
but this will probably have really ugly results.

Also,

> bilingual document with English and Arabic

may be a part of the problem. I don't think that Arabic can be hyphenated (?) which greatly reduces number of possible linebreak positions. This would greatly increase the possibility that no paragraph on a page can be expanded, which would cause lua-widow-control to fail. Something like [“Arabic text justification using LuaLaTeX and the DigitalKhatt OpenType variable font”](https://tug.org/TUGboat/tb42-3/tb132anane-variable.pdf) would probably help, although I don't think that that's usable in regular documents quite yet.

> 2\. What will happen if I load both of these packages in the same document? Will this result in the fewest widows and orphans possible?

`nowidow` internally uses the ε-TeX penalties, and [the manual states that this is unsupported](https://texdoc.org/serve/lua-widow-control/0#page=18). Practically, what this means is that loading `nowidow` will probably just cause lua-widow-control to not work, although it may also mean that weird stuff happens.

You could try something like 
```tex
\lwcsetup{
    widowpenalty = 8000,
    orphanpenalty = 8000,
    brokenpenalty = 8000,
}
```
This will have TeX first try really hard to remove the widows/orphans like `nowidow` does. If it fails, then `lua-widow-control` tries to remove them. You can also combine this with the `emergencystretch` option above if you want.

**Comment by amarakon** [comment]
Thanks for the detailed response. I will try the code you showed me as well.

**Comment by xscheuer** [comment]
Could you add this sentence comparing it to `nowidow` in the documentation?
I had wondered about this myself, and future users will probably do so too. Thanks in advance.

**Comment by gucci-on-fleek** [comment]
@xscheuer 

> Could you add this sentence comparing it to `nowidow` in the documentation? I had wondered about this myself, and future users will probably do so too. Thanks in advance.

Ok, thanks for the suggestion, I've added it to the manual now.
